
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kf-tools--notebooks--notebook-controller
  namespace: "default"
  annotations:
    ## applications in 'kubeflow-tools' come after 'kubeflow-dependencies'
    argocd.argoproj.io/sync-wave: "60"
  labels:
    app.kubernetes.io/name: notebook-controller
    app.kubernetes.io/component: kubeflow-tools
    app.kubernetes.io/part-of: "deploykf"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: "default"
  source:
    repoURL: "https://github.com/MuhamedAyoub/kubeflow_manifests.git"
    targetRevision: "main"
    path: "manifests/kubeflow-tools/notebooks/notebook-controller"
  destination:
    server: "https://kubernetes.default.svc"
    namespace: kubeflow
  ignoreDifferences:
    ## `rules` are aggregated when `aggregationRule.clusterRoleSelectors` is set
    - group: rbac.authorization.k8s.io
      kind: ClusterRole
      jqPathExpressions:
        - "select(.aggregationRule.clusterRoleSelectors | length > 0) | .rules"